### ISSUE TITLE
WAQIAirQuality.City missing `location` field

### ISSUE THREAD

**Issue by jkinkead** [joostlek/python-waqi#31]
# Problem/Motivation

Field "location" is not populated for items pulled from the feed. This is a field on "city" in the JSON response from `/feed/{name}` URLs.

## Expected behavior

`City` (or `Location`) data model has a `location` field containing this string.

## Actual behavior

Field is inaccessible.

## Proposed changes

Adding an optional or required Pydantic field for `location` to at least `City` (the field in `WAQIAirQuality`). I'm not familiar enough with the API to know if it should be required.

**Comment by joostlek** [comment]
we're talking about the location in
```json

        "city": {
            "geo": [
                51.6689355,
                4.541659
            ],
            "name": "Klundert, Brabant",
            "url": "https://aqicn.org/city/netherland/brabant/klundert",
            "location": ""
        },
```
right?

In my experience I couldn't find any that were filled (I also didn't search for them explicitly). Do you have an example json where it's filled? (Or name that I could use)

**Comment by jkinkead** [comment]
The ones coming from Purple Air have it very consistently, like `https://api.waqi.info/feed/A372382/`.

**Comment by jkinkead** [comment]
It's also worth pointing out that these have not-great `name` fields, and appending `name` and `location` yields a similar string to the `name` field in the "native" (?) sensors.

**Comment by joostlek** [comment]
How do you mean native sensors?

**Comment by jkinkead** [comment]
So, I'm new to the WAQI and I have no idea what it's doing. :)

Some locations in the feed like `https://api.waqi.info/feed/@5128/`, represent a city or location in the world, and seem to be provided by WAQI as a first-class entity. The numeric ID of the website URL (`@5128`) matches the feed URL. This looks "native" but I really don't know!

**Comment by joostlek** [comment]
I am also quite new to the API haha. I think I get what you mean. But I don't see any added feature for the library. I now opened a PR where the location string is added to City, and can be a string or None if it's an empty string. Are you fine with that solution?

**Comment by jkinkead** [comment]
Yeah, that works great - thanks!

It looks like you've been working on the Home Assistant integration, which is what I was playing around with as well. I'm trying to update the sensors to support a list of IDs (fixing [this issue](https://github.com/home-assistant/core/issues/96865) more or less), instead of requiring search results, because for whatever reason the search function in my area doesn't return a very complete list of sensors. One part of this fix would be to improve the sensor names with this `location` field. :)

The `dev` branch of `core` (with your latest changes) works a LOT better, btw - and I think [this issue in particular](https://github.com/home-assistant/core/issues/95304) is now fixed. I was hitting that running stable.

**Comment by joostlek** [comment]
Feel free to slide in my dms on discord to discuss about it :) @joostlek

**Comment by joostlek** [comment]
With that station you sent I also discovered that Python 3.10 didn't like the iso string it got. So I removed support for 3.10 as I couldn't be bothered lmao
